[theme]
name = "slick"

[theme.overrides]
# separator = ''

[icons]
name = "awesome5"

[icons.overrides]
backlight_empty = '🌑'
backlight_partial1 = '🌒'
backlight_partial2 = '🌓'
backlight_partial3 = '🌔'
backlight_full = '🌕'


[[block]]
block = "bluetooth"
mac = "58:85:E9:15:6A:A0"
label = ""

[[block]]
block = "kdeconnect"
format = "{bat_charge}% {notif_icon}{notif_count}"
format_disconnected = ''

[[block]]
block = "net"
device = "wlp2s0"
interval = 1
speed_down = true
speed_up = true


[[block]]
block = "networkmanager"
max_ssid_width=21
primary_only=true
device_format = "{icon}{ap}"
connection_format = "{devices}"

[[block]]
block = "custom"
command = "$HOME/dotfiles/jiofi_battery.sh"
interval = 60
json = true

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"
driver = "pulseaudio"
name = "alsa_output.pci-0000_00_1f.3.analog-stereo"
max_vol = 150

[[block]]
block = "cpu"
interval = 1
info = 59

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mupi}%"
format_swap = "{SUpi}%"

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"
critical = 30
warning = 45

[[block]]
block = "time"
interval = 1
format = "%a %d %b %r"
