[theme]
name = "slick"

[theme.overrides]
# separator = ''

[icons]
name = "awesome5"

[icons.overrides]
backlight_empty = '🌑'
backlight_partial1 = '🌒'
backlight_partial2 = '🌓'
backlight_partial3 = '🌔'
backlight_full = '🌕'

[[block]]
block = "focused_window"
max_width = 50

[[block]]
block = "networkmanager"
primary_only=true
device_format = "{icon}{ap}"
connection_format = "{devices}"

[[block]]
block = "custom"
command = "$HOME/dotfiles/jiofi_battery.sh"
interval = 60
json = true

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"
driver = "pulseaudio"
name = "alsa_output.pci-0000_00_1f.3.analog-stereo"

[[block]]
block = "cpu"
interval = 1
info = 59

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mupi}%"
format_swap = "{SUpi}%"

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"
critical = 30
warning = 45

[[block]]
block = "time"
interval = 1
format = "%a %d %b %r"
